### ISSUE TITLE
Calage étrange des ressource sur la home

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/cyberneticproject#2]
<img width="1340" alt="Capture d’écran 2021-09-22 à 14 53 45" src="https://user-images.githubusercontent.com/2088968/134347172-8489be64-f3cb-4dc8-b8cd-566130edce5b.png">

C'est quoi la logique @alexisben ?

**Comment by alexisben** [comment]
Pas normal, je me suis planté quelque part
